Better error handling
rust-embedded/svd2rust pull request #544
Opened 2021-10-31 12:09 UTC by robamu

- More debug output in case something goes wrong in the TokenStream generation
- Some info output in the main

2021-10-31 12:09 UTC, rust-highfive commented
Thanks for the pull request, and welcome! The Rust team is excited to review your changes, and you should hear from @burrbull (or someone else) soon.

Please see [the contribution instructions](https://rustc-dev-guide.rust-lang.org/contributing.html) for more information.

2021-10-31 12:19 UTC, Emilgardis requested changes
nicely done! Some suggestions.

Tracing would be nice to have, but not necessary to implement right now

2021-10-31 12:19 UTC, Emilgardis commented on src/generate/device.rs
> +        out.extend(rendered_peripheral);
This can be done directly in the match, instead of saving as a variable

2021-10-31 12:19 UTC, Emilgardis commented on src/generate/peripheral.rs
> +        ercs_expanded.extend(erc_expanded);
This can be done directly in the match, instead of saving as a variable

2021-10-31 12:19 UTC, Emilgardis commented on src/generate/peripheral.rs
> +        mod_items.extend(rendered_reg);
This can be done directly in the match, instead of saving as a variable

2021-10-31 12:19 UTC, Emilgardis commented on src/generate/peripheral.rs
> +        mod_items.extend(rendered_reg);
This can be done directly in the match, instead of saving as a variable

2021-10-31 12:19 UTC, Emilgardis commented on src/generate/peripheral.rs
> +            new_syn_field(&info_name.to_sanitized_snake_case(), syn_type)
This can be done directly in the match, instead of saving as a variable

2021-10-31 12:19 UTC, Emilgardis commented on src/generate/peripheral.rs
> +    Ok(syn::Type::Path(parsed_path))
```suggestion
    match parse_str::<syn::TypePath>(&ident) {
        Ok(path) => Ok(syn::Type::Path(parsed_path)),
        Err(e) => {
            error!("Determining syn::TypePath from ident \"{}\" failed", ident);
            Err(e)
        }
    }
    
```

2021-10-31 12:19 UTC, Emilgardis commented on src/main.rs
> +            panic!("Error rendering devices: {}", e);
this should not be a panic

2021-10-31 12:19 UTC, Emilgardis commented on src/util.rs
> +fn handle_erc_error(msg: &str, name: &String, descrip: &str) {
why `&String` ?

2021-10-31 12:19 UTC, Emilgardis commented on src/util.rs
> +    eprintln!("\tDescription: {}", descrip);
we should look into switching to `tracing` and make this structured

2021-10-31 12:19 UTC, Emilgardis commented on src/main.rs
> +    info!("Rendering devices..");
```suggestion
    info!("Rendering devices");
```

2021-10-31 12:19 UTC, Emilgardis commented on src/main.rs
> +            panic!("Error parsing SVD file: {}", e);
should not panic

2021-10-31 12:19 UTC, Emilgardis commented on src/generate/device.rs
> +                eprintln!("\tBase address: {:#10x}", p.base_address);
`tracing` would be perfect for this.

2021-10-31 12:24 UTC, burrbull commented
Instead of `log::error!` it is enough to use `anyhow::with_context` here

2021-10-31 12:35 UTC, Emilgardis commented
> 
> 
> Instead of `log::error!` it is enough to use `anyhow::with_context` here

Indeed, however some of these functions return syn::Error, so those would have to be changed as well, but that would bring some better usability like `with_context` :+1:

2021-10-31 16:17 UTC, robamu commented
I integrated most suggestions. Sample output on failure:

```rs
[INFO  svd2rust] Parsing device from SVD file
[INFO  svd2rust] Rendering devices
[ERROR svd2rust] Error rendering devices
    
    Caused by:
        0: Rendering error at peripheral IRQSEL
           Description: Interrupt Selector Peripheral
           Group: No group name
        1: Issue expanding register or cluster block
        2: Error expanding register
           Name: PORTA[%s]
           Description: PORTA Interrupt Redirect Selection
        3: syn error occured
        4: Error converting info name PORTA[%s]
        5: Determining syn::TypePath from ident "crate::Reg<porta%s::PORTA%S_SPEC>" failed
        6: expected `,`
```

2021-10-31 16:24 UTC, burrbull commented
Looks good!

2021-10-31 16:26 UTC, robamu commented
I'm tweaking the output a bit

2021-10-31 16:32 UTC, robamu commented
I think its always just one device which is parsed so I might tweak that output too

2021-10-31 16:33 UTC, burrbull commented
Squash commits, please.

2021-10-31 17:17 UTC, robamu commented
I'll run `rustfmt` and `clippy` and then squash again

2021-10-31 18:44 UTC, Emilgardis requested changes

2021-10-31 18:44 UTC, Emilgardis commented on src/generate/peripheral.rs
> +                    return handle_reg_error("Error redering regular register", *reg, res);
typo, should also not say `regular`
```suggestion
                    return handle_reg_error("Error rendering register", *reg, res);
```

2021-10-31 18:44 UTC, Emilgardis commented on src/generate/peripheral.rs
> +        .with_context(|| "Issue expanding register or cluster block")?;
```suggestion
        .with_context(|| "Could not expand register or cluster block")?;
```

2021-11-01 16:05 UTC, Emilgardis approved these changes
Lgtm! Thank you!

bors r+

2021-11-01 16:10 UTC, Emilgardis commented
bors r-

Sorry, minor nit

2021-11-01 16:12 UTC, Emilgardis requested changes

2021-11-01 16:12 UTC, Emilgardis commented on src/generate/device.rs
> +        out.extend(
Instead of using using the whole match expr,  do `out.extend(periph)` in the Ok branch

Dame thing gor every other occurance of this

2021-11-01 23:03 UTC, Emilgardis requested changes

2021-11-01 23:03 UTC, Emilgardis commented on src/generate/peripheral.rs
> +        mod_items.extend(
one left!

2021-11-02 09:06 UTC, burrbull approved these changes

2021-11-02 09:21 UTC, burrbull commented
bors r+

2021-11-02 09:40 UTC, merged