use expand_properties
rust-embedded/svd2rust pull request #609
Opened 2022-05-10 14:17 UTC by burrbull

2022-05-10 14:17 UTC, rust-highfive commented
r? @ryankurte

(rust-highfive has picked a reviewer for you, use r? to override)

2022-05-10 21:44 UTC, burrbull commented
r? Emilgardis

Partially fixes #610

2022-05-10 23:13 UTC, Emilgardis requested changes

2022-05-10 23:13 UTC, Emilgardis commented on src/generate/peripheral.rs
> +                    "{} can't derive from {}",
```suggestion
                    "{} can't be derived from {}",
```

2022-05-10 23:13 UTC, Emilgardis commented on CHANGELOG.md
> +- Inside peripheral now supported multi-level `deriveFrom` for registers
```suggestion
- Support "nested" `deriveFrom` for registers
```

2022-05-10 23:13 UTC, Emilgardis commented on CHANGELOG.md
> +- Use `expand_properties` from `svd-parser`
don't see why this has to be added to the changelog

2022-05-11 03:39 UTC, burrbull commented
![изображение](https://user-images.githubusercontent.com/3072754/167764315-58ed795c-0bb9-4df3-afa9-19715a5a46f7.png)

MB9AF10xN.svd

Now it is correct

2022-05-11 06:43 UTC, Emilgardis approved these changes

2022-05-11 06:55 UTC, burrbull commented
bors r+

2022-05-11 07:11 UTC, merged