use svd-parser Index (experiment)
rust-embedded/svd2rust pull request #631
Opened 2022-07-17 13:59 UTC by burrbull

2022-07-17 13:59 UTC, rust-highfive commented
r? @Emilgardis

(rust-highfive has picked a reviewer for you, use r? to override)

2022-07-19 11:51 UTC, burrbull commented
cc @qwandor
Test this, please.

2022-07-23 17:48 UTC, burrbull commented
cc @Emilgardis let's merge this

2022-07-23 17:56 UTC, Emilgardis requested changes

2022-07-23 17:56 UTC, Emilgardis commented on src/generate/peripheral.rs
> +                trace!("Cluster: {}", c.name);
move the trace up

```suggestion
            RegisterCluster::Cluster(c) => {
                trace!("Cluster: {}", c.name);
                let mut cpath = None;
                let dpath = c.derived_from.take();
                if let Some(dpath) = dpath {
                    cpath = derive_cluster(c, &dpath, &path, index)?;
                }
                let cpath = cpath.unwrap_or_else(|| path.new_cluster(&c.name));
                
```

2022-07-23 17:56 UTC, Emilgardis commented on src/generate/peripheral.rs
> +                trace!("Register: {}", reg.name);
ditto

2022-07-23 18:09 UTC, burrbull commented on src/generate/peripheral.rs
> +                trace!("Cluster: {}", c.name);
done

2022-07-23 18:15 UTC, Emilgardis approved these changes
bors r+

very nice

2022-07-23 18:32 UTC, merged

2022-07-25 13:25 UTC, qwandor commented
@burrbull The resulting code builds, so that's promising. I haven't had a chance to do any more extensive tests yet.