move hidden into module
rust-embedded/svd2rust pull request #736
Opened 2023-06-14 14:48 UTC by burrbull

2023-08-04 04:26 UTC, burrbull commented
cc @rust-embedded/tools

2023-08-04 14:54 UTC, thejpster commented
v0.29: https://docs.rs/rp2040-pac/latest/rp2040_pac/

![image](https://github.com/rust-embedded/svd2rust/assets/959887/b7bc7f84-9e02-4ea9-92fc-bfc0c2b55fd1)

This patch: 

![image](https://github.com/rust-embedded/svd2rust/assets/959887/51a00cc1-c878-41cd-91c2-4aa2fefc1875)

2023-08-04 14:56 UTC, thejpster commented
I like these changes. But I wonder if there's also scope to try and add some information to this page:

![image](https://github.com/rust-embedded/svd2rust/assets/959887/ee6dffbe-7f45-4928-bab8-fe04daaab2c4)

2023-08-04 15:15 UTC, thejpster requested changes
Slightly change the wording.

2023-08-04 15:15 UTC, thejpster commented on src/generate/register.rs
> +            "\nThis register you can {} with [`R`].",
```suggestion
            "You can {} this register and get [`R`]. ",
```

2023-08-04 15:15 UTC, thejpster commented on src/generate/register.rs
> +            "\nThis register you can {} with [`W`].",
```suggestion
            "You can {} this register using [`W`]. ",
```

2023-08-04 15:15 UTC, thejpster commented on src/generate/register.rs
> +        write!(doc, "\nAnd {} with [`R`] and [`W`].", method("modify"))?;
```suggestion
        write!(doc, "You can also {} this register using [`R`] and [`W`]. ", method("modify"))?;
```

2023-08-04 15:15 UTC, thejpster commented on src/generate/register.rs
> +    doc.push_str("\nSee [API](https://docs.rs/svd2rust/#read--modify--write-api).");
```suggestion
    doc.push_str("\n\nSee [API](https://docs.rs/svd2rust/#read--modify--write-api) for more details.");

2023-08-04 15:15 UTC, thejpster commented on src/generate/register.rs
> +    let mut doc = format!("{description}\n");
```suggestion
    let mut doc = format!("{description}\n\n");
```

2023-08-06 09:48 UTC, burrbull commented
@thejpster 
Now it looks like
![изображение](https://github.com/rust-embedded/svd2rust/assets/3072754/edbc6a7b-cbf7-48e6-9aa2-052c67197b60)
and
![изображение](https://github.com/rust-embedded/svd2rust/assets/3072754/4fc39987-8f5d-40ec-b4fd-0a9b0fe098b3)
accordingly.

2023-08-06 21:37 UTC, thejpster commented
Can we remove the '\n' between the lines? If they have '\n' between them I think they should be a bulleted list. Otherwise I think it should be one paragraph with no new-lines in it.

i.e.

```quote
You can read this register and get somemod::R. You can reset, write, write_with_zero this register and get somemod::W. You can also modify this register.
```

rather than

```quote
You can read this register and get somemod::R.
You can reset, write, write_with_zero this register and get somemod::W. 
You can also modify this register.
```

I also propose expanding on *See API* a little bit.

But these are minor things really. I really like these changes!

2023-08-06 23:10 UTC, burrbull commented
done

2023-08-09 10:24 UTC, thejpster commented
LGTM. Ship it.

2023-08-09 10:24 UTC, thejpster approved these changes

2023-08-09 10:26 UTC, thejpster approved these changes

2023-08-09 10:26 UTC, thejpster commented
So good I managed to approve it twice :/

2023-08-09 10:40 UTC, merged