support of default enum value
rust-embedded/svd2rust pull request #767
Opened 2023-11-21 16:43 UTC by burrbull

2023-11-22 20:04 UTC, burrbull commented
cc @Emilgardis

2023-11-22 20:11 UTC, Emilgardis requested changes

2023-11-22 20:11 UTC, Emilgardis commented on src/generate/register.rs
> +    }
this seems wrong, the repr is wrong now when compared to the actual value on chip

```suggestion
    for (v, c) in variants.iter().chain(std::iter::once(default)).map(|v| {
        let desc = util::escape_special_chars(&util::respace(&format!("{}: {}", v.value, v.doc)));
        let pcv = &v.pc;
        let pcval = &util::unsuffixed(v.value);
        (
            quote! {
                #[doc = #desc]
                #pcv = #pcval,
            },
            quote! {
                #pc::#pcv => #pcval,
            },
        )
    }) {
        vars.extend(v);
        casts.extend(c);
    }
```

2023-11-22 20:11 UTC, Emilgardis commented on src/generate/register.rs
> +    });
this could also be a normal cast when the repr is fixed, or if this can't be fixed we should not use `#[repr(u8)]` and provide a `Into` impl

2023-11-22 20:48 UTC, burrbull commented on src/generate/register.rs
> +    });
I've removed `repr`, but I don't see what is wrong with `From`.

2023-11-22 20:55 UTC, Emilgardis commented on src/generate/register.rs
> +    });
you're right, I mentioned an Into in error

2023-11-22 21:51 UTC, Emilgardis commented on src/generate/register.rs
> +    });
is there a reason repr couldn't be used?

2023-11-23 04:43 UTC, burrbull commented on src/generate/register.rs
> +    });
when I started I thought it is impossible, but after refactoring and when you've asked the question it looks simple.
Now changes much smaller:
![изображение](https://github.com/rust-embedded/svd2rust/assets/3072754/98f3d452-eca2-4ea0-81ba-d300f0f28433)

2023-11-23 07:13 UTC, Emilgardis commented on src/generate/register.rs
> +    });
Awesome!

2023-11-23 07:15 UTC, Emilgardis approved these changes

2023-11-23 07:36 UTC, merged