Add `base-address-shift` configuration flag
rust-embedded/svd2rust pull request #791
Opened 2023-12-25 14:39 UTC by gephaistos

Hello!
We are working with the FPGA-based project and unlike with micro-controllers all peripherals are dynamic.
In order to swap different devices (described within several SVD files) in a single board we need to be able to move their addresses.
That's why in this PR we added a flag to shift all base addresses provided in SVD.

2023-12-25 16:33 UTC, burrbull approved these changes

2023-12-25 16:35 UTC, burrbull commented
Would not it better to generate some global constant and use it calculating `PTR`?

2023-12-25 20:42 UTC, Emilgardis commented
I don't see the reasoning for this, why is the base address in the svd not shifted already?

2023-12-26 09:25 UTC, gephaistos commented
The address might depend on other cores.
For example, if we want to add our core to [these](https://github.com/riscv-steel/riscv-steel) cores the base address should have one value and in the [other case](https://github.com/chipsalliance/caliptra-rtl) it would require another value.
It would be more convenient to be able to change base address value dynamically instead of changing this value in SVD file each time.

2023-12-26 10:21 UTC, burrbull commented
> It would be more convenient to be able to change base address value dynamically instead of changing this value in SVD file each time.

What do you mean under "dynamically" in rust terms?
Is it `const BASE_ADDRESS` or `static mut BASE_ADDRESS`. In second case it can lead to significant downgrade in code optimization.

2023-12-26 10:27 UTC, gephaistos commented
I meant to dynamically shift it from SVD file during generation, not on the Rust side. The PR does exactly this functionality.

2023-12-26 13:03 UTC, thejpster commented
It seems like a niche use-case, but the PR is low-overhead and most people can just ignore the configuration option. Perhaps the help text should be something like:

> This offset will be added to all base addresses on all peripherals in the SVD file. Useful for soft-cores where the peripheral address range isn't necessarily fixed. Ignore this option if you are not building your own FPGA based soft-cores.

2023-12-26 18:32 UTC, Emilgardis requested changes

2023-12-26 18:32 UTC, Emilgardis commented on src/main.rs
> +        )
```suggestion
                .help("Add offset to all base addresses on all peripherals in the SVD file.
Useful for soft-cores where the peripheral address range isn't necessarily fixed.
Ignore this option if you are not building your own FPGA based soft-cores."),
        )
```

2023-12-26 18:36 UTC, Emilgardis commented on src/main.rs
> +        )
Even better would be to use `.long_help("...")` for the additional info

2023-12-26 18:37 UTC, Emilgardis commented on src/main.rs
> +        )
```suggestion
.help("Add offset to all base addresses on all peripherals in the SVD file.")
                .long_help("Add offset to all base addresses on all peripherals in the SVD file.
Useful for soft-cores where the peripheral address range isn't necessarily fixed.
Ignore this option if you are not building your own FPGA based soft-cores."),
        )
```

2024-01-08 08:10 UTC, burrbull submitted a review, later dismissed

2024-01-08 12:09 UTC, Emilgardis submitted a review, later dismissed

2024-01-08 13:10 UTC, burrbull commented
need rebase

2024-01-10 12:12 UTC, burrbull approved these changes

2024-01-10 12:28 UTC, merged